logolas/web/__init__.py
"""Web module."""

logolas/web/app.py
"""Web application."""

from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy #pylint: disable=E0611,F0401
from logolas.model import get_table

db = SQLAlchemy() #pylint: disable=C0103

def _config(configuration):
    """Get Logolas web configuration."""

    fields = []
    for patterns in configuration.get_file_to_patterns().values():
        for pattern in patterns.values():
            fields.extend(pattern['fields'])

    fields = list(frozenset(fields))

    tables = []
    for patterns in configuration.get_file_to_patterns().values():
        for name, pattern in patterns.items():
            pair = get_table(db.metadata, name, pattern['fields'], pattern['order'])
            tables.append(pair)

    return { 'fields': fields, 'tables': tables }

def application(configuration):
    """Application factory."""

    app = Flask(__name__)

    from logolas.web.routes import logolas
    app.register_blueprint(logolas)

    app.config['SQLALCHEMY_DATABASE_URI'] = configuration.get_database_uri()

    db.init_app(app)

    app.config['logolas'] = _config(configuration)

    app.logger.debug(app.config['logolas'])

    return app

logolas/web/routes.py
"""Routes."""

from flask import render_template, jsonify, Blueprint, current_app, request
from flask.ext.sqlalchemy import SQLAlchemy #pylint: disable=E0611,F0401
from logolas.web.query import is_search_applicable, get_query_filter
from logolas.web.url import get_filters
from sqlalchemy import desc

logolas = Blueprint('logolas', __name__, template_folder='templates') #pylint: disable=C0103

db = SQLAlchemy() #pylint: disable=C0103

@logolas.route('/')
def index():
    """Render main index page."""
    return render_template('index.html')

@logolas.route('/field')
def field():
    """Retrieve fields list."""
    return jsonify(fields=current_app.config['logolas']['fields'])

@logolas.route('/log')
def log():
    """Retrieve log entries."""

    filters = get_filters(request.args)
    limit   = int(request.args['limit'])

    current_app.logger.debug("Request (limit %s) %s", limit, filters)

    logs = []
    for (table, model) in current_app.config['logolas']['tables']:
        if is_search_applicable(table.columns, filters):
            query = db.session.query(model)

            columns = dict((column.name, column) for column in table.columns)

            logic = get_query_filter(columns, filters)

            query = query.filter(logic).order_by(desc(columns['time'])).limit(limit)

            current_app.logger.debug(query)

            for row in query.all():
                logs.append({
                    'time': str(row.time),
                    'id':   row.id,
                    'type': table.name,
                    'hash': '%s%s' % (table.name, row.id), # hash is used by the UI to avoid collisions
                    'data': row.get_data(),
                })

    # The query sort is only to ensure the query limit gives us the right data set. Here we actually sort the results.
    logs = sorted(logs, key=lambda log: log['time'])

    # The query limit only narrows the number of results we get. Here we actually cut it off at limit.
    logs = logs[-limit:]

    return jsonify(logs=logs)

logolas/web/templates/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
        <title>Logolas</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css" />
        <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/jquery.maskedinput.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/script.js') }}" type="text/javascript"></script>
    </head>
    <body>
        <h1>Logolas</h1>
        <h2 id="javascript_notice">Please enable JavaScript</h2>
        <script type="text/javascript">
            document.getElementById("javascript_notice").style.display = "none";

            $().ready(function() {
                Logolas('{{ url_for('logolas.field') }}', '{{ url_for('logolas.log') }}');
            });
        </script>
        <div id="filter">
            <h2>Filter</h2>
            <form action="{{ url_for('logolas.log') }}" method="get">
                <fieldset>
                </fieldset>
                <label>
                    Limit
                    <input type="text" name="limit" value="100" />
                </label>
            </form>
        </div>
        <div id="logs">
        </div>
    </body>
</html>